### PR TITLE
Main localize search

### PR DESCRIPTION
**Pull request by SurfaceS**
added possibility to ask find with language param (help finding the right one when title is in locale language).
it always return en-US results, language is just used to find the tmdbID, not the data.
added test for it.

As we lake of tmdbID for previously found MediaMetadata, I added code to update MediaMetadata tmdbID from localized if requested without tmdbID.

### CODE REVIEW

**Review by SubJunk — COMMENTED** [review]
I added a suggestion. Also I can drop our current database of results at any time, and I have done that before, particularly after releasing code fixes that improve results. So maybe I can do that instead of having the code that updates the tmdb, what do you think?

**Comment by SurfaceS** [comment]
In fact, it should not update so much, as client update tmdbID on his side the same way.
So requests will synergize itself.

> I can drop our current database of results.

I think we can do that on a much bigger change, like movies and tv episodes having their own table.

**Review by SubJunk — APPROVED** [review]

**Comment by SubJunk** [comment]
Approved, will merge and deploy in a few hours

**Comment by SubJunk** [comment]
That's deployed now

**Pull request merged**
